issue/TAPC-16 done
rbagrov/python_fundamentals pull request #31
Opened 2018-07-07 14:32 UTC by EmiliyanPanagyurski

2018-07-09 17:25 UTC, rbagrov requested changes

2018-07-09 17:25 UTC, rbagrov commented on week3/emo/addUser.py
> +   connection.set(user['username'], user)
Isn't this what you've ment?

```python
connection.set(user['username'], user['password'])
```

2018-07-09 17:25 UTC, rbagrov commented on week3/emo/authentication/authenticate.py
> +                if userExists == 'nil':
When ```userExists``` can be string and this string can have value of ```nil``` ?

2018-07-09 17:25 UTC, rbagrov commented on week3/emo/authentication/authenticate.py
> +                    print('User is already in the database')
You are actually not storing even valid users.

2018-07-09 17:25 UTC, rbagrov commented on week3/emo/authentication/authenticate.py
> +                print('password must be longer than ' + str(passwordLength))
Please use ```.format```

2018-07-09 17:25 UTC, rbagrov commented on week3/emo/db/connection.py
> +connection = redis.StrictRedis(host='localhost', port=6379, db=0)
```
HOST = 'localhost'
PORT = 6379
DB = 0

connection = redis.StrictRedis(host=HOST, port=PORT, db=DB)

2018-07-09 17:25 UTC, rbagrov commented on week3/emo/db/connection.py
> +import redis
Where do you install ```redis``` ?

2018-07-09 19:24 UTC, EmiliyanPanagyurski commented on week3/emo/authentication/authenticate.py
> +                if userExists == 'nil':
Yes actually it can!

2018-07-09 19:25 UTC, EmiliyanPanagyurski commented on week3/emo/db/connection.py
> +import redis
I have a question about the requirements in chat.you might want to check it.

2018-07-09 20:08 UTC, rbagrov commented on week3/emo/authentication/authenticate.py
> +                if userExists == 'nil':
Please check here: https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L973-L977

2018-07-10 17:51 UTC, EmiliyanPanagyurski commented on week3/emo/addUser.py
> +   connection.set(user['username'], user)
No, the key corresponds to a dict!

2018-07-10 17:58 UTC, EmiliyanPanagyurski commented on week3/emo/authentication/authenticate.py
> +                    print('User is already in the database')
How come? Please elaborate!

2018-07-10 19:49 UTC, rbagrov commented on week3/emo/authentication/authenticate.py
> +                    print('User is already in the database')
I don't remember when I checked that it has the client class. Anyways now setting works.

2018-07-10 19:50 UTC, rbagrov commented on week3/emo/authentication/authenticate.py
> +                if userExists == None:
better representations would be: ```if not userExists:```

2018-07-10 19:51 UTC, rbagrov commented on week3/emo/db/client.py
> +        if result == 'nil':
Please check this:
```
In [2]: from db.connection import connection

In [3]: connection.get('pesho')
Out[3]: b"{'password': '121312321321312', 'username': 'pesho'}"

In [4]: connection.get('ddd')

In [5]: connection.get('ddd') is None
Out[5]: True

In [6]: connection.get('ddd') == 'nil'
Out[6]: False

```

2018-07-10 19:52 UTC, rbagrov reviewed
Check this out

2018-07-10 19:53 UTC, rbagrov commented on week3/emo/authentication/authenticate.py
> +                if userExists == None:
or ```if userExists is None```

2018-07-12 07:44 UTC, rbagrov approved these changes

2018-07-12 07:45 UTC, merged